import React from "react";
import {
  ScrollView,
  Text,
  View,
  StyleSheet,
  Linking,
  TouchableOpacity,
} from "react-native";

const privacy = () => {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.h1}>Privacy Policy</Text>
      <Text style={styles.date}>Last updated: August 05, 2025</Text>

      <Text style={styles.p}>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </Text>

      <Text style={styles.p}>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. .
      </Text>

      <Text style={styles.h2}>Interpretation and Definitions</Text>
      <Text style={styles.h3}>Interpretation</Text>
      <Text style={styles.p}>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </Text>

      <Text style={styles.h3}>Definitions</Text>
      <Text style={styles.p}>For the purposes of this Privacy Policy:</Text>

      {[
        [
          "Account",
          "means a unique account created for You to access our Service or parts of our Service.",
        ],
        [
          "Affiliate",
          'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
        ],
        [
          "Application",
          "refers to Anydle, the software program provided by the Company.",
        ],
        ["Company", "refers to Anydle."],
        ["Country", "refers to: Jammu and Kashmir, India"],
        [
          "Device",
          "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
        ],
        [
          "Personal Data",
          "is any information that relates to an identified or identifiable individual.",
        ],
        ["Service", "refers to the Application."],
        [
          "Service Provider",
          "means any natural or legal person who processes the data on behalf of the Company.",
        ],
        [
          "Usage Data",
          "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
        ],
        [
          "You",
          "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
        ],
      ].map(([title, desc], idx) => (
        <View key={idx} style={styles.li}>
          <Text style={styles.p}>
            <Text style={styles.bold}>{title}</Text> — {desc}
          </Text>
        </View>
      ))}

      <Text style={styles.h2}>Collecting and Using Your Personal Data</Text>
      <Text style={styles.h3}>Types of Data Collected</Text>
      <Text style={styles.h4}>Personal Data</Text>
      <Text style={styles.p}>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </Text>

      {["Email address", "First name and last name", "Usage Data"].map(
        (item, i) => (
          <Text key={i} style={styles.li}>
            • {item}
          </Text>
        )
      )}

      <Text style={styles.h4}>Usage Data</Text>
      <Text style={styles.p}>
        Usage Data is collected automatically when using the Service and may
        include info such as your IP address, browser type, pages visited,
        time/date of visit, mobile device type, OS, etc.
      </Text>

      <Text style={styles.h3}>Use of Your Personal Data</Text>
      <Text style={styles.p}>
        The Company may use Personal Data for the following purposes:
      </Text>

      {[
        "To provide and maintain our Service, including to monitor the usage of our Service.",
        "To manage Your Account: to manage Your registration as a user of the Service.",
        "For the performance of a contract: fulfilling purchase contracts or other agreements.",
        "To contact You: for updates, offers, or important service-related communication.",
        "To provide You with news, special offers and general information.",
        "To manage Your requests: attend and manage Your requests to Us.",
        "For business transfers: evaluate or conduct restructuring, merger, sale of assets, etc.",
        "For other purposes: analytics, performance review, marketing optimization, etc.",
      ].map((text, idx) => (
        <Text key={idx} style={styles.li}>
          • {text}
        </Text>
      ))}

      <Text style={styles.p}>
        We may share Your personal information in the following situations:
      </Text>

      {[
        "With Service Providers: to monitor and analyze the use of our Service, or to contact You.",
        "For business transfers: during negotiations of any acquisition or sale.",
        "With Affiliates: such as parent/subsidiary companies, under this same Privacy Policy.",
        "With business partners: to offer You certain products or services.",
        "With other users: when shared in public areas.",
        "With Your consent: for any purpose with Your permission.",
      ].map((text, idx) => (
        <Text key={idx} style={styles.li}>
          • {text}
        </Text>
      ))}

      <Text style={styles.h3}>Retention of Your Personal Data</Text>
      <Text style={styles.p}>
        We retain data as long as necessary for legal, functional, and
        analytical purposes.
      </Text>

      <Text style={styles.h3}>Transfer of Your Personal Data</Text>
      <Text style={styles.p}>
        Your data may be transferred and maintained on servers outside your
        country. We ensure adequate safeguards are in place for such transfers.
      </Text>

      <Text style={styles.h3}>Delete Your Personal Data</Text>
      <Text style={styles.p}>
        You have the right to request deletion of your data. You may also manage
        data within your account or contact us directly.
      </Text>

      <Text style={styles.h3}>Disclosure of Your Personal Data</Text>
      <Text style={styles.h4}>Business Transactions</Text>
      <Text style={styles.p}>
        If involved in a merger or acquisition, your data may be transferred.
      </Text>

      <Text style={styles.h4}>Law enforcement</Text>
      <Text style={styles.p}>
        We may disclose data when legally required to comply with obligations or
        requests.
      </Text>

      <Text style={styles.h4}>Other legal requirements</Text>
      <Text style={styles.p}>
        Disclosure may be necessary to protect rights, investigate misuse,
        ensure safety, or defend legal liability.
      </Text>

      <Text style={styles.h3}>Security of Your Personal Data</Text>
      <Text style={styles.p}>
        While we use commercially acceptable means to secure data, no method is
        100% secure.
      </Text>

      <Text style={styles.h2}>Children's Privacy</Text>
      <Text style={styles.p}>
        We do not knowingly collect data from children under 13. If you believe
        your child has provided data, contact us to remove it.
      </Text>

      <Text style={styles.h2}>Links to Other Websites</Text>
      <Text style={styles.p}>
        We are not responsible for the privacy policies of external websites.
        Please review them before proceeding.
      </Text>

      <Text style={styles.h2}>Changes to this Privacy Policy</Text>
      <Text style={styles.p}>
        We may update this Privacy Policy from time to time and will notify You
        accordingly. Changes become effective when posted.
      </Text>

      <Text style={styles.h2}>Contact Us</Text>
      <View
        style={[
          {
            marginBottom: 50,
            flexDirection: "row",
            display: "flex",
            gap: 5,
          },
        ]}
      >
        <Text style={styles.p}>Contact us at:</Text>
        <Text
          style={styles.link}
          onPress={() => Linking.openURL("mailto:ashai.daamin@gmail.com")}
        >
          ashai.daamin@gmail.com
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
    flex: 1,
    backgroundColor: "#121213",
  },
  h1: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#f8f8f8",
  },
  h2: {
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 8,
    color: "#f8f8f8",
  },
  h3: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#f8f8f8",
    marginTop: 16,
    marginBottom: 4,
  },
  h4: {
    fontSize: 16,
    fontWeight: "600",
    color: "#f8f8f8",
    marginTop: 12,
    marginBottom: 4,
  },
  date: {
    marginBottom: 16,
    fontStyle: "italic",
    color: "#f8f8f8",
  },
  p: {
    fontSize: 14,
    marginBottom: 12,
    color: "#f8f8f8",
    lineHeight: 20,
  },
  li: {
    fontSize: 14,
    marginLeft: 10,
    marginBottom: 8,
    color: "#f8f8f8",
    lineHeight: 20,
    flexDirection: "row",
  },
  bold: {
    fontWeight: "bold",
    color: "#f8f8f8",
  },
  link: {
    color: "#1e90ff",
    textDecorationLine: "underline",
  },
});

export default privacy;
